In [1]:
import re
import time
import requests
import warnings
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import matplotlib.pyplot as plt
import seaborn as sns


warnings.filterwarnings('ignore')

In [2]:
productname = []
price = []
rating = []
features = []
pagenum = []
original_price = []
Discount = []
Review = []

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/154.0.0.0 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.7"
}

total_time = time.time()

for page_num in range(1, 42):

    start_time = time.time()

    URL = f"https://www.flipkart.com/search?q=laptop&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_1_4_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_1_4_na_na_na&as-pos=1&as-type=RECENT&suggestionId=laptop%7CLaptops&requestId=3f3ea89d-e660-48a9-b1a4-5c9c322da66e&as-searchtext=Lapt&page={page_num}"

    page = requests.get(URL, headers=headers, timeout=15)
    page.raise_for_status()

    soup = BeautifulSoup(page.text, 'html.parser')

    for x in soup.find_all('div', attrs={'class': 'ZFwe0M row'}):

        pname = x.find('div', attrs={'class': 'RG5Slk'})
        cost = x.find('div', attrs={'class': 'hZ3P6w DeU9vF'})
        rat = x.find('div', attrs={'class': 'MKiFS6'})
        specs = x.find('div', attrs={'class': 'CMXw7N'})
        op = x.find('div', attrs={'class': 'kRYCnD gxR4EY'})
        discount = x.find('div', attrs={'class': 'HQe8jr'})
        reviews = x.find('span', attrs={'class': 'PvbNMB'})

        productname.append(pname.get_text(strip=True) if pname else np.nan)
        price.append(cost.get_text(strip=True) if cost else np.nan)
        rating.append(rat.get_text(strip=True) if rat else np.nan)
        features.append(specs.get_text(" ", strip=True) if specs else np.nan)
        original_price.append(op.get_text(strip=True) if op else np.nan)
        Discount.append(discount.get_text(strip=True) if discount else np.nan)
        Review.append(reviews.get_text(strip=True) if reviews else np.nan)

        pagenum.append(page_num)

    print(f"Page {page_num} completed in {time.time()-start_time:.2f} seconds")

    time.sleep(1)

print("Total Time Completed in seconds:", time.time() - total_time)

Page 1 completed in 1.39 seconds
Page 2 completed in 2.28 seconds
Page 3 completed in 1.15 seconds
Page 4 completed in 1.75 seconds
Page 5 completed in 1.33 seconds
Page 6 completed in 1.73 seconds
Page 7 completed in 1.10 seconds
Page 8 completed in 2.31 seconds
Page 9 completed in 1.72 seconds
Page 10 completed in 1.55 seconds
Page 11 completed in 1.52 seconds
Page 12 completed in 1.22 seconds
Page 13 completed in 1.33 seconds
Page 14 completed in 1.80 seconds
Page 15 completed in 1.14 seconds
Page 16 completed in 1.27 seconds
Page 17 completed in 1.23 seconds
Page 18 completed in 1.25 seconds
Page 19 completed in 1.91 seconds
Page 20 completed in 1.14 seconds
Page 21 completed in 1.25 seconds
Page 22 completed in 1.23 seconds
Page 23 completed in 1.09 seconds
Page 24 completed in 1.12 seconds
Page 25 completed in 1.29 seconds
Page 26 completed in 1.35 seconds
Page 27 completed in 1.34 seconds
Page 28 completed in 1.34 seconds
Page 29 completed in 1.35 seconds
Page 30 completed in 1.41 seconds
Page 31 completed in 1.55 seconds
Page 32 completed in 1.52 seconds
Page 33 completed in 1.29 seconds
Page 34 completed in 1.28 seconds
Page 35 completed in 1.20 seconds
Page 36 completed in 1.26 seconds
Page 37 completed in 1.19 seconds
Page 38 completed in 1.39 seconds
Page 39 completed in 1.36 seconds
Page 40 completed in 2.07 seconds
Page 41 completed in 1.81 seconds
Total Time Completed in seconds: 99.83225440979004

In [3]:
df1 = pd.DataFrame({
    "Product Name": productname,
    "Price": price,
    "Original Price": original_price,
    "Discount": Discount,
    "Rating": rating,
    "Reviews": Review,
    "Features": features,
    "Page Number": pagenum
})

In [9]:
display(df1.shape)
display(df1.head())
display(df1.columns)
display(df1.isnull().sum())

(984, 8)

,Product Name,Price,Original Price,Discount,Rating,Reviews,Features,Page Number
0,Lenovo IdeaPad Slim 5 OLED Display Intel Core ...,"₹1,39,990","₹2,30,290",39% off,4.2,15 Ratings&1 Reviews,Intel Core Ultra 9 Processor 16 GB DDR5 RAM Wi...,1
1,MOTOROLA Motobook 60 Full Metal WUXGA OLED (i5...,"₹66,990","₹1,35,000",50% off,4.4,"3,885 Ratings&509 Reviews",Intel Core 5 Processor 16 GB DDR5 RAM 64 bit W...,1
2,Lenovo 100e Chromebook Gen 4 MediaTek Kompanio...,"₹22,544","₹25,999",13% off,4,"3,712 Ratings&361 Reviews",MediaTek Kompanio 520 Processor 4 GB LPDDR4X R...,1
3,Acer Aspire Lite Metal (2026) AMD Ryzen 3 Quad...,"₹36,990","₹52,990",30% off,4.1,"1,015 Ratings&105 Reviews",AMD Ryzen 3 Quad Core Processor 8 GB DDR4 RAM ...,1
4,Ultimus Elite Intel Core i5 10th Gen 1035G4 - ...,"₹45,990",NaN,NaN,3.6,542 Ratings&135 Reviews,Intel Core i5 Processor (10th Gen) 8 GB DDR4 R...,1

Index(['Product Name', 'Price', 'Original Price', 'Discount', 'Rating',
       'Reviews', 'Features', 'Page Number'],
      dtype='object')

Product Name        0
Price               8
Original Price    205
Discount          222
Rating            175
Reviews           175
Features            0
Page Number         0
dtype: int64

In [10]:
df1.to_csv('scrapped_data.csv',index=False)

In [11]:
df=pd.read_csv('scrapped_data.csv')
df

,Product Name,Price,Original Price,Discount,Rating,Reviews,Features,Page Number
0,Lenovo IdeaPad Slim 5 OLED Display Intel Core ...,"₹1,39,990","₹2,30,290",39% off,4.2,15 Ratings&1 Reviews,Intel Core Ultra 9 Processor 16 GB DDR5 RAM Wi...,1
1,MOTOROLA Motobook 60 Full Metal WUXGA OLED (i5...,"₹66,990","₹1,35,000",50% off,4.4,"3,885 Ratings&509 Reviews",Intel Core 5 Processor 16 GB DDR5 RAM 64 bit W...,1
2,Lenovo 100e Chromebook Gen 4 MediaTek Kompanio...,"₹22,544","₹25,999",13% off,4.0,"3,712 Ratings&361 Reviews",MediaTek Kompanio 520 Processor 4 GB LPDDR4X R...,1
3,Acer Aspire Lite Metal (2026) AMD Ryzen 3 Quad...,"₹36,990","₹52,990",30% off,4.1,"1,015 Ratings&105 Reviews",AMD Ryzen 3 Quad Core Processor 8 GB DDR4 RAM ...,1
4,Ultimus Elite Intel Core i5 10th Gen 1035G4 - ...,"₹45,990",NaN,NaN,3.6,542 Ratings&135 Reviews,Intel Core i5 Processor (10th Gen) 8 GB DDR4 R...,1
...,...,...,...,...,...,...,...,...
979,HP 14s Intel Core i5 11th Gen 1135G7 - (8 GB/5...,"₹69,990","₹74,990",6% off,4.2,274 Ratings&22 Reviews,Intel Core i5 Processor (11th Gen) 8 GB DDR4 R...,41
980,ASUS ExpertBook P1 with 1 Yr ADP (i5 14th Gen)...,"₹74,990","₹1,14,990",34% off,4.2,233 Ratings&24 Reviews,Intel Core 5 Processor 32 GB DDR5 RAM 64 bit W...,41
981,ASUS ExpertBook P1 with 1 Yr ADP (i3 14th Gen)...,"₹56,990","₹99,990",43% off,NaN,NaN,Intel Core 3 Processor 8 GB DDR5 RAM 64 bit Wi...,41
982,HP 15s Intel Core i5 13th Gen 1335U - (8 GB/51...,"₹72,990","₹82,699",11% off,4.2,422 Ratings&30 Reviews,Intel Core i5 Processor (13th Gen) 8 GB DDR4 R...,41
983,HP 15s Intel Core i5 12th Gen 1235U - (8 GB/51...,"₹72,990","₹75,899",3% off,4.2,"2,274 Ratings&155 Reviews",Intel Core i5 Processor (12th Gen) 8 GB DDR4 R...,41